### ISSUE TITLE
Firmware versie wordt niet goed weergegeven

### ISSUE THREAD

**Issue by TomNagel123** [PimDoos/ha-sessy#31]
Ik draai op 0.1.0 van jouw integratie

Ik heb firmware 1.1.2 in de dongle en in de battery zitten, maar Device info toont 1.1.1
![image](https://user-images.githubusercontent.com/98328845/229103896-30922288-35cb-4a4a-b6e7-86a067030586.png)

NU ben in geupdated naar jouw 0.1.2 *en* heb ik (verplicht) HA opnieuw opgestart. Nu toont het info panel wel de juiste versie.

**Comment by PimDoos** [comment]
Fixed in [v0.2.3](https://github.com/PimDoos/ha-sessy/releases/tag/v0.2.3)

**Comment by PimDoos** [comment]
No quite fixed. Working on a new implementation
