### ISSUE TITLE
Discharge power is too restrictive

### ISSUE THREAD

**Issue by TomNagel123** [PimDoos/ha-sessy#37]
The specification of the Sessy is 1700W discharge on the website, but it can do more at high battery voltages.
The real restriction is the maximum current that the BIC power supply inside the Sessy can handle (37.5A). 
So when battery voltage is above 45V (which is always), it can do more than 1700W.
When the battery is full, it will have around 54V, meaning we can discharge at 2025W

There is no harm in allowing to set 2000W via the API in Home Assistant. The Sessy will try to reach whatever you set, but will not go over the limits of the components inside the Sessy.

My request is that the limit of 1700W discharge is increased to 2000W

**Comment by PimDoos** [comment]
Sounds reasonable.
Since it can go slightly over 2000W, I'll go ahead and adjust the range to [-2200,+2200] to make the limit symmetrical. It then matches the maximum power entity, which also has 2200W as maximum value.

**Comment by TomNagel123** [comment]
excellent!

**Comment by PimDoos** [comment]
Fixed in [v0.2.2](https://github.com/PimDoos/ha-sessy/releases/tag/v0.2.2)
