### ISSUE TITLE
Button to once fully charge Sessy?

### ISSUE THREAD

**Issue by StevenLooman** [PimDoos/ha-sessy#69]
Now that winter is coming in the northern hemisphere, there will be days that the solar panels will not produce enough to charge the Sessy. Given the high/low-tariff system in The Netherlands, it would be nice if the Sessy can charge at night (lower tariff), when the next day will be a day with low/no solar power production, and discharge during the day (high tariff).

Although you can choose the manual strategy in the Sessy, it says something like: With great power comes great responsibility. Rightfully so. I don't wish to implement my own strategy (and control the Sessy). But I'd like to have a one-time-button with which I can say: Charge now until full, from net power. Yes, this is fully manual but at least the "damage" will be limited to one day, compared to a faulty strategy which keeps running.

Is this possible? Or would this be something that should be implemented on the Sessy itself? Perhaps @MartijnCharged can elaborate on this as well.

**Comment by PimDoos** [comment]
I don't think this should be implemented on the integration, but rather as an automation or script. The integration only proxies Sessy's API methods, and fully charging is not one of them.
I do have a Home Assistant script in place which sets the strategy to API and starts charging until the battery is full. I'll polish it up a bit and publish it on [ha-sessy-examples](https://github.com/PimDoos/ha-sessy-examples) as a blueprint.

**Comment by StevenLooman** [comment]
I fully agree. It was mostly meant as an opener/gathering information, as I can imagine more people have the same question. Hence, also the tagging of @MartijnCharged.

> I do have a Home Assistant script in place which sets the strategy to API and starts charging until the battery is full. I'll polish it up a bit and publish it on [ha-sessy-examples](https://github.com/PimDoos/ha-sessy-examples) as a blueprint.

Great, thank you!

**Comment by dacootmeister** [comment]
> I don't think this should be implemented on the integration, but rather as an automation or script. The integration only proxies Sessy's API methods, and fully charging is not one of them. I do have a Home Assistant script in place which sets the strategy to API and starts charging until the battery is full. I'll polish it up a bit and publish it on [ha-sessy-examples](https://github.com/PimDoos/ha-sessy-examples) as a blueprint.

appreciated! I too am interested in such logic as a hybrid strategy is season dependant.

**Comment by StevenLooman** [comment]
Thank you for your response Martijn. I appreciate you are coordinating with Pim to make sure this component works properly.

I was not asking for a new strategy (although I can see this strategy might be useful during certain times); I was asking for a one-time button to start charging up to 100%/fully charged. My idea is that if you know the next day is going to be cloudy (and thus low solar-power-production, most likely resulting in a discharged battery), you can click a button and the Sessy will charge itself from the network.

Of course, it is fully understandable (to me) you might not want to add this. A simpler product is usually better. This one-time action can probably be achieved via a blueprint or some custom strategy as already noted by Pim. On the other hand, with this button my own set-up becomes simpler. And perhaps other people might would like functionality like this as well (at least one .

**Comment by jpduhen** [comment]
I think a new strategy would be nice in which the Sessy charges when not fully charged during low energy prices at nighttime, when energy prices are higher in the morning. Like in this graph: ![image](https://github.com/PimDoos/ha-sessy/assets/45515609/9e7c58a3-804c-48e9-82e5-6ed9223823e1)When fully charged (or when prices are going up) switch to NOM.
Same with low energy prices during a cloudy day, when the solarpanels are not charging the Sessy to full, also charge at low cost, to cover evening and early night NOM.
(Btw could the update yesterday be responsible for breaking my HA integration?)
You're all doing a nice job!

**Comment by PimDoos** [comment]
Implemented as a blueprint script in [ha-sessy-examples](https://github.com/PimDoos/ha-sessy-examples#sessy-full-charge-script)

**Comment by jpduhen** [comment]
Thank you all, I think this blueprint will help me to build something like this in HA.
@MartijnCharged I still think the low-cost-night-charge strategy (charge Sessy to 100% at night when energy is cheap) would be also nice to have to achieve NOM in the morning hours.

**Comment by StevenLooman** [comment]
Thank you for providing the blueprint @PimDoos!

> this request does have a lot of dependency's, like the expected solar power, the expected home usage and possibly even low tariff charging. i think its awesome if you manage to get this working!

I was not asking for a new strategy, just a one-time action. That way the Sessy side stays simpler, but it is up to the user to determine when to run the action.

However, given the blueprint I think I am satisfied for now. Again, thank you.
