### ISSUE TITLE
Foutmelding bij koppelen aan sessy na update

### ISSUE THREAD

**Issue by RobAltorf** [PimDoos/ha-sessy#74]
In v0.5.2 krijg ik mijn batterij niet meer gekoppeld.
de P1 dongle doet het wel gewoon.

bij apparaat toevoegen heb ik zowel het sessy-XXXX.local adres geprobeerd als het ip adres. Beide resulteren in een onbekende fout.
Onderstaande foutmelding heb ik uit de log gekregen
Mijn Sessy is ongeveer een week geleden geïnstalleerd. De eerste paar dagen werkte deze integratie nog wel.
De laatste firmware is geïnstalleerd op de Sessy.

Op de pagina van de Sessy zelf (zowel het IP adres als de sessy-XXXX.local) kan ik gewoon inloggen en zie ik ook gewoon de data van de sessy.

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.sessy.config_flow
Source: custom_components/sessy/config_flow.py:34
Integration: Sessy (documentation, issues)
First occurred: 10:51:22 (9 occurrences)
Last logged: 11:47:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/sessy/config_flow.py", line 94, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sessy/config_flow.py", line 34, in validate_input
    device = await get_sessy_device(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sessypy/devices.py", line 131, in get_sessy_device
    raise SessyNotSupportedException
sessypy.util.SessyNotSupportedException

**Comment by RobAltorf** [comment]
Toevoeging:
Zojuist heeft Home assistant de batterij herkent met auto discovery, maar ook dan blijft deze foutmelding als je wilt configureren

**Comment by PimDoos** [comment]
In v0.5.2 zijn de netwerk timeouts teruggeschroeft, waardoor Sessy binnen 5 seconden moet reageren op een API request.
Heeft de dongle van de accu voldoende WiFi dekking? Of is deze aangesloten met een netwerkkabel?

Wat is de response tijd in de browser? Dat kun je testen via de DevTools (F12 of CTRL+SHIFT+C --> Network tab)
![2023-10-10_13-30-51-1e0b30f215_msedge](https://github.com/PimDoos/ha-sessy/assets/17709721/304b1602-fb98-4850-9bbf-d840c4feac9c)

**Comment by RobAltorf** [comment]
response tijd is 100ms
![image](https://github.com/PimDoos/ha-sessy/assets/49553620/53f33bae-81a5-4a60-a357-9f10d7bb8036)

Signaalsterkte wifi: -75 dB

**Comment by PimDoos** [comment]
Kun je wat debug logs verzamelen?

In configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.sessy: debug
    sessypy: debug
```

**Comment by RobAltorf** [comment]
Jouw opmerking zette me aan het denken. Vanaf mijn laptop is de verbinding ontzettend snel. Vanaf mijn home assistant server niet. Dus waarschijnlijk zit er iets raars in mijn netwerk. (laptop is wifi naar router, server is draad naar router). Zal wel een configuratie dingetje zijn. 
Ik sluit hem voor nu. Als ik mijn server ook snel heb en het probleem bestaat nog steeds, dan open ik hem wel opnieuw
