### ISSUE TITLE
CT dongle Total Power

### ISSUE THREAD

**Issue by eavyon** [PimDoos/ha-sessy#75]
In the current version the total power sensor is a factor 1000 off. Its displaying watts as kW.

CT dongle firmware 1.5.3

**Comment by eavyon** [comment]
Only in HA where this integration is used for. The api is correct. I've tried changing the precision in HA to make it more clear.
![image](https://github.com/PimDoos/ha-sessy/assets/84970882/0c3fe8e9-ad59-446c-a97d-730b01e06df1)
![image](https://github.com/PimDoos/ha-sessy/assets/84970882/1c95bc1d-c74c-4801-9a13-6345311aa199)

**Comment by PimDoos** [comment]
Looks like a mistake in the sensor definition. Didn't catch this as my development CT meter does not measure any power.
https://github.com/PimDoos/ha-sessy/blob/7203397a117f0a6552fc455236a20f3d13ea9aad/custom_components/sessy/sensor.py#L183

Unit should be `WATT` and suggested unit should be `KILO_WATT`, just like sensor definition for the P1 meter total power. Will patch this later today.
