### ISSUE TITLE
Efficientie sensor 

### ISSUE THREAD

**Issue by UPS90** [PimDoos/ha-sessy#80]
Bij het omzetten van stroom treden verliezen op, deze zijn afhankelijk van laden / ontladen en het vermogen. Is het mogelijk een efficiënte waarde toe te voegen om zo het perfecte laad en ontlaad vermogen vast te stellen?

**Comment by PimDoos** [comment]
Sessy heeft testdata gepubliceerd op hun website over de efficientste vermogens. Dat ligt ruwweg tussen de 800 en 1200 W.
https://www.sessy.nl/technische-achtergrond-informatie/

Om realtime efficiëntie uit te rekenen moet er meer data uit de Sessy API worden gehaald, zoals DC en AC vermogen. Op dit moment is die data niet beschikbaar in de API. Als dit wordt toegevoegd aan de API, komt dit ook in de integratie.
