### ISSUE TITLE
Dynamic mode schedule and EPEX energy price api

### ISSUE THREAD

**Issue by MartijnCharged** [PimDoos/ha-sessy#85]
As described at https://github.com/PimDoos/sessypy/issues/29

**Comment by berendhaan** [comment]
When will the PR related to this issue be merged and released?

**Comment by PimDoos** [comment]
I haven't taken the time yet to figure out how to implement the schedules into HA yet. With the firmware 1.6.5 now generally available, this feature will be in the next release of ha-sessy.

**Comment by berendhaan** [comment]
Do you mean the technical part or how to map it in to HA?

The HA Zonneplan integration sets an array of values for the upcoming prices. 

![image](https://github.com/PimDoos/ha-sessy/assets/634641/505babda-6508-4c9c-a121-2c4b98e80219)

**Comment by PimDoos** [comment]
Working on an implementation in dev now. Seems to work and am able to get it to render in ApexCharts.
![image](https://github.com/PimDoos/ha-sessy/assets/17709721/0232c07a-03a9-4117-9c8a-814de5f06902)

**Comment by PimDoos** [comment]
If this survives DST without bugs I'll probably release it next week.

**Comment by DvdEnde** [comment]
wow! looking good!Op vr 29 mrt 2024 om 22:24 schreef Pim ***@***.***>
If this survives DST without bugs I'll probably release it next week.

**Comment by PimDoos** [comment]
Seems to still be working fine! Doing some final tweaks/testing and releasing soon.
![image](https://github.com/PimDoos/ha-sessy/assets/17709721/b5edd187-8bdc-49bf-ae3b-ce85c8176e90)

**Comment by dacootmeister** [comment]
> Seems to still be working fine! Doing some final tweaks/testing and releasing soon. ![image](https://private-user-images.githubusercontent.com/17709721/318301486-b5edd187-8bdc-49bf-ae3b-ce85c8176e90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA0NTgsIm5iZiI6MTcxMjc1MDE1OCwicGF0aCI6Ii8xNzcwOTcyMS8zMTgzMDE0ODYtYjVlZGQxODctOGJkYy00OWJmLWFlM2ItY2U4NWM4MTc2ZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDExNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjYyNWNkMGFhODFlZmI3MDU0ODU5ODBmYWRhOTI2YTY4MDU3MDA5YjllOGJhZThiMTE4OGZmNzFmN2FmNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMKbMuLrnRSPv6iyJwoGIGrB14jAfkBK6GQbnF763Go)

may I ask which sensors you used and what math is applied for the data to show just like in your examples Pim?

**Comment by PimDoos** [comment]
See https://github.com/PimDoos/ha-sessy-examples/blob/main/cards/DynamicSchedule.md

**Comment by dacootmeister** [comment]
> See https://github.com/PimDoos/ha-sessy-examples/blob/main/cards/DynamicSchedule.md

What a treat! Thanks for your effort Pim :-D
