### ISSUE TITLE
[Feature Request] configure sensor.sessy_XXXX_state_of_charge entity to track statistics

### ISSUE THREAD

**Issue by RogierSchuring** [PimDoos/ha-sessy#96]
I am unable to add the state of charge to a Statistics graph Card in HA. HA tells me that the developer should configure the entity so they know that they need to track statistics for that entity. Could you do so or maybe give a hint on how to add the state of charge percentage to a graph?

Link HA gives: https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by PimDoos** [comment]
The state of charge sensor already sets a `device_class` and `state_class`, so you should see statistics being generated. In my instance, I am able to add these sensors just fine.
![image](https://github.com/PimDoos/ha-sessy/assets/17709721/1d7b8ee4-8f44-461b-bcc3-53fdf6d1f611)
![image](https://github.com/PimDoos/ha-sessy/assets/17709721/47da9fc2-4f0f-4074-91d8-049f6805058f)


Are you sure you are not mixing sensors with different units in the statistics card? 
Can you check the [developer tools for statistics](https://my.home-assistant.io/redirect/developer_statistics/) to see if the entities have any issues?

**Comment by RogierSchuring** [comment]
Hmm... my bad. Was not expecting that two sensors with different units could not be displaid in the same statistics card.
When trying to add it in a new statistics card, it shows up.

**Comment by RogierSchuring** [comment]
Closed
